# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthday', models.DateField(blank=True)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
